[package]
name = "encrypt_project"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cli-clipboard = "0.4.0"
rand = "0.8.5"
slint = "1.4.1"

[build-dependencies]
slint-build = "1.4.1"


